config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :users do
    post :reset_password
    post :change_password
    get :check_email

    resource :sessions, only: [:new, :create, :destroy] do
    end
  end

  resources :users, only: [:show, :create, :update] do
    resources :widgets, only: [:index], controller: "users/widgets"
  end

  resources :widgets, only: [:index, :new, :create, :update, :destroy]

  match "widgets/visible" => "widgets#visible", :via => :get
  root to: 'widgets#visible'
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  before_action -> { redirect_to user_widgets_path(current_user.try(:id)) }, if: :logged_in?, only: [:new, :create]

  def new
    @user_vm = UserVm.new
  end

  def create
    if login(UserVm.new(user_params_require))
      redirect_to user_widgets_path(:me)
    else
      redirect_to root_path
    end
  end

  def destroy
    if logout
      flash[:success] = "Logged out successfully."
    end

    redirect_to root_path
  end

  def reset_passwords
    reset_password(UserVm.new(user_params_require))
    redirect_to root_path
  end

  private

  def user_params_require
    params.require(:user_vm).permit(:email, :password)
  end
end

app/controllers/users/widgets_controller.rb
class Users::WidgetsController < ApplicationController
  include AuthenticatorConcerns
  include UserWidgetsConcerns

  def index
    @user_id  = params[:user_id]
    @all_widgets = user_id_widgets(@user_id, params[:term])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include AuthenticatorConcerns
  include UserConcerns
  skip_before_action :authenticate, only: [:create, :reset_password, :check_email]

  def create
    @user_vm = UserVm.new(user_params_require)
    if @user_vm.valid?
      create_user(@user_vm)
    else
      flash[:danger] = @user_vm.errors.full_messages.join(", ")
    end

    redirect_to root_path
  end

  def update
    @user_vm = UserVm.new(user_params_require)

    if @user_vm.valid?
      update_user(@user_vm)
    else
      flash[:danger] = @user_vm.errors.full_messages.join(", ")
    end

    redirect_to user_path(current_user.try(:id))
  end

  def show
    @user_vm = show_user(UserVm.new(id: params[:id]))
  end

  def reset_password
    user_reset_password(UserVm.new(email: params[:user_vm][:email]))
    redirect_to root_path
  end

  def change_password
    user_vm = current_user
    user_vm.old_password = params[:user_vm][:old_password]
    user_vm.password = params[:user_vm][:password]
    user_vm.password_confirmation = params[:user_vm][:password_confirmation]

    if user_vm.valid?
      user_change_password(user_vm)
    else
      flash[:danger] = user_vm.errors.full_messages.join(", ")
    end

    redirect_to user_widgets_path(current_user.try(:id))
  end

  def check_email
    @user_vm = UserVm.new(email: params[:user_vm].try(:[], :email))
    user_check_email(@user_vm) if @user_vm.email.present?
  end

  private

  def user_params_require
    params.require(:user_vm).permit!
  end
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users/widgets_helper.rb
module Users::WidgetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_change_password_modal.html.haml
.modal#change_password{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5.modal-title Change password
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = form_for user_vm, url: users_change_password_path, remote: true do |f|
          = render "users/form_fields", f: f, action_type: "change_password"
          %button.btn.btn-primary{:type => "submit"} Update
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close

app/views/users/_edit_modal.html.haml
.modal#edit_user{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5.modal-title Edit user
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = form_for current_user, url: user_path(current_user.try(:id)), method: :patch do |f|
          = render "users/form_fields", f: f, action_type: "edit_user"
          %button.btn.btn-primary{:type => "submit"} Update
          %a{"data-toggle": "modal", "data-target": "#change_password", onclick: "$(this).parents('.modal').modal('hide');"}= "Change password"
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close

= render "users/change_password_modal", user_vm: current_user

app/views/users/_form_fields.html.haml
- action_type ||= nil

- case action_type
- when "new_session"
  .form-group
    %label Email
    = f.text_field :email, {"aria-describedby" => "emailHelp", :placeholder => "Enter email", :type => "email", :class => "form-control"}
  .form-group
    %label Password
    = f.password_field :password, {"aria-describedby" => "passwordHelp", :placeholder => "Enter Password", :class => "form-control"}

- when "new_user"
  .form-group
    %label Email
    = f.text_field :email, {"aria-describedby" => "emailHelp", :placeholder => "Enter email", :type => "email", :class => "form-control"}
  .form-group
    %label Password
    = f.password_field :password, {"aria-describedby" => "passwordHelp", :placeholder => "Enter Password", :class => "form-control"}
  .form-group
    %label Password confirmation
    = f.password_field :password_confirmation, {"aria-describedby" => "passwordConfirmationHelp", :placeholder => "Enter Password confirmation", :class => "form-control"}
  .form-group
    %label First name
    = f.text_field :first_name, {"aria-describedby" => "firstName", :placeholder => "Enter Firstname", :class => "form-control"}
  .form-group
    %label Last name
    = f.text_field :last_name, {"aria-describedby" => "lastName", :placeholder => "Enter Lastname", :class => "form-control"}
  .form-group
    %label Image URL
    = f.text_field :image_url, {"aria-describedby" => "imageUrl", :placeholder => "Enter Image Url", :class => "form-control"}
  .form-group
    %label Date of birth
    = f.text_field :date_of_birth, class: :flatpickr

- when "edit_user"
  .form-group.text-center
    %img.img-fluid{src: current_user.images["small_url"] }
  .form-group
    %label Email
    = f.text_field :email, {"aria-describedby" => "emailHelp", :placeholder => "Enter email", :type => "email", :class => "form-control"}
  .form-group
    %label First name
    = f.text_field :first_name, {"aria-describedby" => "firstName", :placeholder => "Enter Firstname", :class => "form-control"}
  .form-group
    %label Last name
    = f.text_field :last_name, {"aria-describedby" => "lastName", :placeholder => "Enter Lastname", :class => "form-control"}
  .form-group
    %label Date of birth
    = f.text_field :date_of_birth, class: :flatpickr
  .form-group
    %label Image URL
    = f.text_field :image_url, {"aria-describedby" => "imageUrl", :placeholder => "Enter Image Url", :class => "form-control"}

- when "change_password"
  .form-group.text-center
    %img.img-fluid{src: current_user.images["small_url"] }
  .form-group
    %label Old Password
    = f.password_field :old_password, {"aria-describedby" => "oldPasswordHelp", :placeholder => "Enter Old Password", :class => "form-control"}
  .form-group
    %label New Password
    = f.password_field :password, {"aria-describedby" => "newPasswordHelp", :placeholder => "Enter New Password", :class => "form-control"}
  .form-group
    %label New Password confirmation
    = f.password_field :password_confirmation, {"aria-describedby" => "newPasswordConfirmationHelp", :placeholder => "Enter New Password confirmation", :class => "form-control"}

app/views/users/_new_modal.html.haml
- user_vm ||= UserVm.new

.modal#signup{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5.modal-title Sign up
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = form_for user_vm, url: users_path do |f|
          = render "users/form_fields", f: f, action_type: "new_user"
          %button.btn.btn-primary{:type => "submit"} Sign up
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close

app/views/users/check_email.html.haml
.container
  .text-center
    %h3 Enter user email to check
    = form_for @user_vm, url: users_check_email_path, method: :get do |f|
      .field
        = f.label :email
        = f.text_field :email
      = f.submit :check, class: "btn btn-primary"

app/views/users/show.html.haml
.container
  .text-center
    .field
      %img{src: @user_vm.try(:images).try(:[], "large_url")}
    %br
    .field
      %label First name:
      = @user_vm.first_name
    .field
      %label Last name:
      = @user_vm.last_name
    .field
      %label Date of birth:
      %span.flatpickr= @user_vm.date_of_birth
    = link_to "Show Widgets", user_widgets_path(@user_vm.id)