config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :users do
    post :reset_password
    post :change_password
    get :check_email

    resource :sessions, only: [:new, :create, :destroy] do
    end
  end

  resources :users, only: [:show, :create, :update] do
    resources :widgets, only: [:index], controller: "users/widgets"
  end

  resources :widgets, only: [:index, :new, :create, :update, :destroy]

  match "widgets/visible" => "widgets#visible", :via => :get
  root to: 'widgets#visible'
end

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark
  %a.navbar-brand{:href => root_path}
    = image_tag "show_off_logo", class: "img-fluid"
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => root_path}
          Home
      %li.nav-item.dropdown.active
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Widgets
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          - if logged_in?
            %a.dropdown-item{:href => user_widgets_path(:me)} My Widgets
            %a.dropdown-item{:href => new_widget_path} New Widget
            %a.dropdown-item{:href => widgets_path} Edit Widgets
          %a.dropdown-item{:href => root_path} Visible Widgets
      - if logged_in?
        %li.nav-item.active
          %a.nav-link{:href => user_path(:me)}
            My Profile
      %li.nav-item.active
        %a.nav-link{:href => users_check_email_path}
          Check email
    .actions
      - if logged_in?
        %button.btn.btn-outline-primary{"data-toggle": "modal", "data-target": "#edit_user"}= current_user.try(:name)
        = link_to "Logout", users_sessions_path, method: :delete, class: "btn btn-primary"
        = render "users/edit_modal", user_vm: current_user
      - else
        = render "users/sessions/login_modal"
        = render "users/new_modal"
        %button.btn.btn-primary{"data-toggle": "modal", "data-target": "#login"}= "Login"
        %button.btn.btn-primary{"data-toggle": "modal", "data-target": "#signup"}= "Sign up"

app/views/shared/_widget_card.html.haml
- show_widget_actions ||= false

.widget
  .text-center
    %h4
      = widget_vm.name
  .description
    %span= "Description: "
    %span= widget_vm.description
  .kind
    %span= "Visibility: "
    %span= widget_vm.kind
  .user
    - user = widget_vm.user
    %span= "Owner: "
    = link_to user.try(:[], "name"), user_path(user.try(:[], "id"))
  - if show_widget_actions.present?
    .row
      .col-12
        .actions.float-right
          %button.btn.btn-primary{onclick: "widgetEditModal(#{widget_vm.to_json})"} Edit
          = link_to "Delete", widget_path(widget_vm.id), method: :delete, remote: true,  data: { confirm: "Are you sure you want to destroy #{widget_vm.name} widget? " }, class: "btn btn-warning"