config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :users do
    post :reset_password
    post :change_password
    get :check_email

    resource :sessions, only: [:new, :create, :destroy] do
    end
  end

  resources :users, only: [:show, :create, :update] do
    resources :widgets, only: [:index], controller: "users/widgets"
  end

  resources :widgets, only: [:index, :new, :create, :update, :destroy]

  match "widgets/visible" => "widgets#visible", :via => :get
  root to: 'widgets#visible'
end

app/controllers/users/widgets_controller.rb
class Users::WidgetsController < ApplicationController
  include AuthenticatorConcerns
  include UserWidgetsConcerns

  def index
    @user_id  = params[:user_id]
    @all_widgets = user_id_widgets(@user_id, params[:term])
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  include AuthenticatorConcerns
  include WidgetsConcerns
  skip_before_action :authenticate, only: :visible

  def index
    @all_widgets = all_widgets
  end

  def new
    @widget_vm = WidgetVm.new
  end

  def create
    @widget_vm = WidgetVm.new(widget_params_require)
    if @widget_vm.valid?
      if create_widget(@widget_vm)
        redirect_to user_widgets_path(current_user.id)
        return
      end
    else
      flash[:danger] = @widget_vm.errors.full_messages.join(", ")
    end

    redirect_to new_widget_path
  end

  def update
    widget_vm = WidgetVm.new(widget_params_require)
    widget_vm.id = params[:id]

    if widget_vm.valid?
      update_widget(widget_vm)
    else
      flash[:danger] = widget_vm.errors.full_messages.join(", ")
    end

    redirect_to widgets_path
  end

  def destroy
    widget_vm = WidgetVm.new(id: params[:id])
    destroy_widget(widget_vm)
    redirect_to user_widgets_path(:me)
  end

  def visible
    @all_widgets = visible_widgets(params[:term])
  end

  private

  def widget_params_require
    params.require(:widget_vm).permit(:name, :description, :kind)
  end
end

app/helpers/users/widgets_helper.rb
module Users::WidgetsHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_edit_mustache_form.html.haml
#mustache_form
  = form_for WidgetVm.new, url: "" do |f|
    = hidden_field_tag :_method, :patch
    = hidden_field_tag :authenticity_token, form_authenticity_token

    .field
      = f.label :name
      = f.text_field :name, value: "{{widget_name}}"
    .field
      = f.label :description
      = f.text_field :description, value: "{{widget_description}}"
    .field
      = f.label :visibility
      = f.select :kind, WidgetVm::KINDS
    = f.submit :update, class: "btn btn-primary"

app/views/widgets/_edit_mustache_modal.html.haml
.modal#edit_widget_modal{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5.modal-title Edit widget
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close

:javascript
  $(document).ready(function() {
    window.widget_mustache_form_template = `#{ render 'widgets/edit_mustache_form' }`;
  })

app/views/widgets/index.html.haml
.container
  .text-center
    %br
    %h2= "Total widgets: #{@all_widgets.count} widgets"
  .row
    - @all_widgets.each do |widget_vm|
      .col-12-.col-sm-6
        = render "shared/widget_card", widget_vm: widget_vm, show_widget_actions: true

= render "widgets/edit_mustache_modal"

app/views/widgets/new.html.haml
.container
  .text-center
    %h1 Add New widget
    = form_for @widget_vm, url: widgets_path, remote: true do |f|
      .field
        = f.label :name
        = f.text_field :name
      .field
        = f.label :description
        = f.text_field :description
      .field
        = f.label :visibility
        = f.select :kind, WidgetVm::KINDS
      = f.submit :create, class: "btn btn-primary"

app/views/widgets/visible.html.haml
.container
  .text-center
    %br
    %h2= "Total visible widgets: #{@all_widgets.count} widgets"
    .term
      = form_tag widgets_visible_path, method: :get do |f|
        = text_field_tag :term, params[:term]
        = submit_tag "Search widget", class: "btn btn-primary"
  %br
  .row
    - @all_widgets.each do |widget_vm|
      .col-12-.col-sm-6
        = render "shared/widget_card", widget_vm: widget_vm